/**
 * Session-scoped workspace manager.
 *
 * Problem: multiple developers pointing at the same Flutter project
 * clobber each other's build state — `.dart_tool/`, `build/`,
 * `ios/Pods/`, `android/.gradle/`, `pubspec.lock`, etc. are all
 * shared and get rewritten by every concurrent `flutter run`.
 *
 * Solution: each *session* that runs Flutter gets its own snapshot
 * of the origin project on disk. Source files (lib/, test/, assets/,
 * pubspec.yaml, platform folders MINUS their build caches) are copied
 * into `<root>/<sessionId>/`; the mutable build directories start
 * empty. The Flutter subprocess uses the snapshot as its cwd, so
 * every write it does lands inside the snapshot and cannot affect
 * either the origin OR any other session.
 *
 * Lifecycle:
 *   • prepare(sessionId, originPath, opts) — creates the snapshot
 *     lazily on first call. Subsequent prepare() calls for the same
 *     session return the existing snapshot as long as originPath
 *     matches (a session is bound to one origin).
 *   • release(sessionId) — rm -rf the snapshot. Idempotent.
 *   • reapOrphans() — server startup housekeeping: any snapshots on
 *     disk from a previous (crashed) process are dead and must be
 *     removed before new sessions collide with them.
 *
 * Modes:
 *   • 'copy'   — default; native fs.cpSync with a filter. On Linux
 *                this uses copy_file_range; on macOS APFS it uses
 *                clonefile (near-instant reflinks). Very fast in
 *                practice for modest projects.
 *   • 'shared' — no isolation; workspaces map straight back to the
 *                origin path. Legacy behaviour, kept for opt-out.
 *
 * The public API is deliberately narrow so we can swap the copy
 * strategy later (git worktree / OverlayFS / hardlink) without
 * touching FlutterRunner.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const logger = {
  info:  (m, d = {}) => console.log (`[WORKSPACE][INFO]  ${new Date().toISOString()} - ${m}`, Object.keys(d).length ? d : ''),
  warn:  (m, d = {}) => console.warn(`[WORKSPACE][WARN]  ${new Date().toISOString()} - ${m}`, Object.keys(d).length ? d : ''),
  error: (m, d = {}) => console.error(`[WORKSPACE][ERROR] ${new Date().toISOString()} - ${m}`, Object.keys(d).length ? d : ''),
};

/**
 * Directories (relative to project root) that must be started fresh
 * per session. Anything that Flutter, Dart, pub, CocoaPods, Gradle,
 * or Xcode may write to during a build should be listed here — if
 * we let two sessions share these dirs the whole isolation model
 * falls over.
 *
 * Path separators are always '/' in this list. Comparison against
 * the filesystem-native separator happens in the filter.
 */
const DEFAULT_EXCLUDE_DIRS = Object.freeze([
  // Flutter / Dart tool state.
  '.dart_tool',
  'build',
  // VCS / IDE detritus we don't need in the snapshot. Skipping .git
  // also avoids copying repos with huge object DBs.
  '.git',
  '.hg',
  '.svn',
  '.idea',
  '.vscode',
  // Node modules if the project has JS-side tooling (unlikely at
  // pubspec.yaml level but common when the checkout has a monorepo
  // sibling — cheap to filter out).
  'node_modules',
  // iOS build state.
  'ios/Pods',
  'ios/.symlinks',
  'ios/Flutter/Flutter.framework',
  'ios/Flutter/App.framework',
  'ios/build',
  'ios/DerivedData',
  // macOS build state.
  'macos/Pods',
  'macos/.symlinks',
  'macos/Flutter/ephemeral',
  'macos/build',
  'macos/DerivedData',
  // Android build state.
  'android/.gradle',
  'android/.kotlin',
  'android/build',
  'android/app/build',
  'android/captures',
  // Desktop platforms.
  'linux/flutter/ephemeral',
  'linux/build',
  'windows/flutter/ephemeral',
  'windows/build',
  // Web build output.
  'web/build',
  // Never recurse into our own workspace root if it happens to sit
  // inside a project checkout.
  '.session-workspaces',
]);

/**
 * Individual files (relative to project root) to skip. These are
 * regenerated by `flutter run` / `pub get` so shipping stale copies
 * only invites bugs.
 */
const DEFAULT_EXCLUDE_FILES = Object.freeze([
  '.flutter-plugins',
  '.flutter-plugins-dependencies',
  '.packages',                     // legacy Dart package layout
  'android/local.properties',      // machine-specific SDK path
]);

class SessionWorkspaceManager {
  /**
   * @param {object} opts
   * @param {string} opts.root                      Absolute directory that holds all per-session snapshots.
   * @param {'copy'|'shared'} [opts.mode='copy']    Default isolation mode.
   * @param {string[]} [opts.excludeDirs]           Extra dir patterns to exclude (added to DEFAULT_EXCLUDE_DIRS).
   * @param {string[]} [opts.excludeFiles]          Extra file names to exclude (added to DEFAULT_EXCLUDE_FILES).
   * @param {number} [opts.snapshotTimeoutMs=120000] How long a single snapshot may take before we abort.
   */
  constructor(opts) {
    this.root = path.resolve(opts.root);
    this.defaultMode = opts.mode ?? 'copy';
    this.snapshotTimeoutMs = opts.snapshotTimeoutMs ?? 120_000;
    this.defaultExcludeDirs = new Set([
      ...DEFAULT_EXCLUDE_DIRS,
      ...(Array.isArray(opts.excludeDirs) ? opts.excludeDirs : []),
    ]);
    this.defaultExcludeFiles = new Set([
      ...DEFAULT_EXCLUDE_FILES,
      ...(Array.isArray(opts.excludeFiles) ? opts.excludeFiles : []),
    ]);
    /** @type {Map<string, WorkspaceInfo>} */
    this.workspaces = new Map();
    /** @type {Map<string, Promise<WorkspaceInfo>>} */
    this._inflight = new Map();

    fs.mkdirSync(this.root, { recursive: true });
  }

  /**
   * Create (or return the existing) workspace for a session.
   *
   * Two sessions calling prepare() concurrently against the same
   * `sessionId` share the SAME promise, so we never build the same
   * snapshot twice. This matters because run_flutter is idempotent
   * on the client (retries, reconnections).
   *
   * @param {string} sessionId
   * @param {string} originPath      Absolute path to the origin Flutter project.
   * @param {object} [opts]
   * @param {'copy'|'shared'} [opts.mode]
   * @param {string[]} [opts.excludeDirs]
   * @param {string[]} [opts.excludeFiles]
   * @returns {Promise<WorkspaceInfo>}
   */
  async prepare(sessionId, originPath, opts = {}) {
    if (!sessionId) throw new Error('prepare(): sessionId is required');
    if (!originPath) throw new Error('prepare(): originPath is required');
    const absOrigin = path.resolve(originPath);
    const mode = opts.mode ?? this.defaultMode;

    if (mode === 'shared') {
      // Legacy behaviour: no isolation. Return a synthesised info so
      // callers don't need a special code path.
      const info = {
        sessionId,
        workspacePath: absOrigin,
        origin: absOrigin,
        mode: 'shared',
        isolated: false,
        createdAt: Date.now(),
      };
      return info;
    }

    // Reuse across repeated prepare() calls in the same session.
    const existing = this.workspaces.get(sessionId);
    if (existing) {
      if (existing.origin !== absOrigin) {
        throw new Error(
          `Session ${sessionId} is already bound to workspace for ${existing.origin}; ` +
          `refusing to rebind to ${absOrigin}. Close (destroy_session) and retry.`
        );
      }
      return existing;
    }
    if (this._inflight.has(sessionId)) {
      return this._inflight.get(sessionId);
    }

    const promise = (async () => {
      const workspacePath = path.join(this.root, sessionId);
      // Guard against leftovers from a crashed prior server: rm -rf
      // any orphan at this path before we start.
      try {
        fs.rmSync(workspacePath, { recursive: true, force: true, maxRetries: 3 });
      } catch (err) {
        logger.warn('pre-snapshot cleanup failed', { sessionId, workspacePath, error: err.message });
      }
      fs.mkdirSync(workspacePath, { recursive: true });

      const excludeDirs = new Set([
        ...this.defaultExcludeDirs,
        ...(Array.isArray(opts.excludeDirs) ? opts.excludeDirs : []),
      ]);
      const excludeFiles = new Set([
        ...this.defaultExcludeFiles,
        ...(Array.isArray(opts.excludeFiles) ? opts.excludeFiles : []),
      ]);

      const startedAt = Date.now();
      await this._snapshot(absOrigin, workspacePath, excludeDirs, excludeFiles);
      const elapsedMs = Date.now() - startedAt;

      const info = {
        sessionId,
        workspacePath,
        origin: absOrigin,
        mode: 'copy',
        isolated: true,
        createdAt: startedAt,
        snapshotElapsedMs: elapsedMs,
      };
      this.workspaces.set(sessionId, info);
      logger.info('workspace prepared', {
        sessionId, origin: absOrigin, workspacePath, elapsedMs,
      });
      return info;
    })();

    this._inflight.set(sessionId, promise);
    try { return await promise; }
    finally { this._inflight.delete(sessionId); }
  }

  /**
   * Delete the snapshot associated with a session. Safe to call for
   * unknown sessions; safe to call twice.
   *
   * We DO NOT touch shared-mode workspaces (they point at the origin
   * — nuking would delete the user's project).
   */
  async release(sessionId) {
    const info = this.workspaces.get(sessionId);
    if (!info) return;
    this.workspaces.delete(sessionId);
    if (!info.isolated) return; // shared mode — nothing to remove.

    try {
      fs.rmSync(info.workspacePath, { recursive: true, force: true, maxRetries: 3 });
      logger.info('workspace released', {
        sessionId, workspacePath: info.workspacePath, ageMs: Date.now() - info.createdAt,
      });
    } catch (err) {
      // Not fatal: reapOrphans() on next startup will clean it up.
      logger.warn('workspace release failed', {
        sessionId, workspacePath: info.workspacePath, error: err.message,
      });
    }
  }

  /**
   * Called at server startup. Any directory under `this.root` is a
   * snapshot from a previous (crashed / restarted) server run and
   * has to go — the sessions it belonged to are dead.
   */
  async reapOrphans() {
    let entries;
    try {
      entries = fs.readdirSync(this.root, { withFileTypes: true });
    } catch (err) {
      if (err.code === 'ENOENT') return;
      logger.warn('reap: cannot read workspace root', { root: this.root, error: err.message });
      return;
    }
    let removed = 0;
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      const p = path.join(this.root, e.name);
      try {
        fs.rmSync(p, { recursive: true, force: true, maxRetries: 3 });
        removed++;
      } catch (err) {
        logger.warn('reap: rmSync failed', { path: p, error: err.message });
      }
    }
    if (removed > 0) {
      logger.info('reaped orphan workspaces from previous run', { root: this.root, removed });
    }
  }

  /** Introspection for status endpoints. */
  stats() {
    return {
      root: this.root,
      defaultMode: this.defaultMode,
      active: this.workspaces.size,
      workspaces: [...this.workspaces.values()].map((info) => ({
        sessionId: info.sessionId,
        workspacePath: info.workspacePath,
        origin: info.origin,
        mode: info.mode,
        isolated: info.isolated,
        ageMs: Date.now() - info.createdAt,
        snapshotElapsedMs: info.snapshotElapsedMs,
      })),
    };
  }

  // ── internals ────────────────────────────────────────────────────────

  /**
   * Copy origin → workspace with our exclude filters applied.
   *
   * We use fs.cpSync (stable in Node 18) with a filter. Under the
   * hood Node forwards to the fastest platform-native copy primitive
   * available (copy_file_range on Linux, clonefile on macOS APFS,
   * CopyFileEx on Windows). No shell-out to `cp`/`xcopy`.
   */
  _snapshot(origin, workspace, excludeDirs, excludeFiles) {
    // fs.cpSync is synchronous; wrap in a Promise for callers that
    // want to await it, and impose a soft timeout so a runaway copy
    // (huge project + slow disk) doesn't hang a WS request forever.
    return new Promise((resolve, reject) => {
      let done = false;
      const timer = setTimeout(() => {
        if (done) return;
        done = true;
        reject(new Error(
          `Snapshot exceeded ${this.snapshotTimeoutMs}ms — origin=${origin}. ` +
          `Consider adding heavy directories to workspace.excludeDirs, or set mode="shared".`
        ));
      }, this.snapshotTimeoutMs);

      // fs.cpSync yields the event loop between syscalls internally
      // in recent Node, but for very large projects consider swapping
      // this for an async walker. Fine as a first cut.
      setImmediate(() => {
        try {
          fs.cpSync(origin, workspace, {
            recursive: true,
            errorOnExist: false,
            force: true,
            preserveTimestamps: false,
            dereference: false,
            filter: (src) => this._shouldCopy(src, origin, excludeDirs, excludeFiles),
          });
          if (done) return;
          done = true;
          clearTimeout(timer);
          resolve();
        } catch (err) {
          if (done) return;
          done = true;
          clearTimeout(timer);
          reject(err);
        }
      });
    });
  }

  /**
   * `fs.cpSync` filter. Return true to include the entry, false to
   * skip it (and its descendants).
   *
   * Comparison is done on FORWARD-SLASH-normalised relative paths so
   * config authors don't have to worry about Windows separators.
   */
  _shouldCopy(src, origin, excludeDirs, excludeFiles) {
    const rel = path.relative(origin, src);
    if (rel === '' || rel === '.') return true;
    const relPosix = rel.split(path.sep).join('/');

    for (const excl of excludeDirs) {
      if (relPosix === excl) return false;
      if (relPosix.startsWith(excl + '/')) return false;
    }
    if (excludeFiles.has(relPosix)) return false;

    return true;
  }
}

/**
 * WorkspaceInfo shape (typedef for callers).
 * @typedef {object} WorkspaceInfo
 * @property {string} sessionId
 * @property {string} workspacePath  Absolute; use as flutter's cwd.
 * @property {string} origin         Absolute origin project path.
 * @property {'copy'|'shared'} mode
 * @property {boolean} isolated      false only when mode === 'shared'.
 * @property {number} createdAt
 * @property {number} [snapshotElapsedMs]
 */

// ── singleton wiring ──────────────────────────────────────────────────

let _singleton = null;

/**
 * Build the singleton from a raw config object (typically loaded
 * from flutter-projects.json's top-level `workspace` block). Called
 * once at server startup — subsequent calls are no-ops.
 */
function initFromConfig(config = {}) {
  if (_singleton) return _singleton;
  const cfg = config.workspace ?? {};
  const defaultRoot = path.join(__dirname, '..', '.session-workspaces');
  _singleton = new SessionWorkspaceManager({
    root: path.resolve(cfg.root || defaultRoot),
    mode: cfg.mode || 'copy',
    excludeDirs: Array.isArray(cfg.excludeDirs) ? cfg.excludeDirs : undefined,
    excludeFiles: Array.isArray(cfg.excludeFiles) ? cfg.excludeFiles : undefined,
    snapshotTimeoutMs: Number.isFinite(cfg.snapshotTimeoutMs) ? cfg.snapshotTimeoutMs : undefined,
  });
  // Fire-and-forget: startup housekeeping. Doesn't block server
  // ready — worst case one orphan lingers until the next restart.
  _singleton.reapOrphans().catch(() => {});
  return _singleton;
}

function get() {
  if (!_singleton) {
    // Lazy-init with defaults so callers never crash on missing setup.
    return initFromConfig();
  }
  return _singleton;
}

/**
 * Test-only: replace the singleton. Do not call from production code.
 */
function _resetForTests(instance) {
  _singleton = instance ?? null;
}

module.exports = {
  SessionWorkspaceManager,
  initFromConfig,
  get,
  DEFAULT_EXCLUDE_DIRS,
  DEFAULT_EXCLUDE_FILES,
  _resetForTests,
};
